pool:
  vmImage: 'Ubuntu 18.04'

trigger:
  - master


#Your build pipeline references a secret variable named ‘DB_PASSWORD_DEV_TEST’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references a secret variable named ‘AZURE_STORAGE_SECRET_KEY_DEV’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
variables:
  DB_HOST_DEV_TEST: 'dmapps-dev-mysql.mysql.database.azure.com'
  DB_PORT: '3306'
  DB_NAME_DEV: 'dmapps_dev'
  DB_USER_DEV_TEST: 'pipeline_user@dmapps-dev-mysql'
  DB_PASSWORD_DEV_TEST: '$(DB_PASSWORD_DEV_TEST)'
  AZURE_STORAGE_ACCOUNT_NAME_DEV: 'dmappsdev'
  AZURE_STORAGE_SECRET_KEY_DEV: '$(AZURE_STORAGE_SECRET_KEY_DEV)'

steps:
  - script: |
      # install pre-requisites
      python -m pip install --upgrade pip setuptools wheel
      sudo apt-get install libmysqlclient-dev
      pip install -r requirements.txt

      # create env file
      python create_env_file.py --db-host "$(DB_HOST_DEV_TEST)" --db-port "$(DB_PORT)" --db-name "$(DB_NAME_DEV)" --db-user "$(DB_USER_DEV_TEST)" --db-password "$(DB_PASSWORD_DEV_TEST)" --azure-storage-account-name "$(AZURE_STORAGE_ACCOUNT_NAME_DEV)" --azure-storage-secret-key "$(AZURE_STORAGE_SECRET_KEY_DEV)" --in-pipeline "True"

      # run migrations and collect static files
      python manage.py migrate
      python manage.py collectstatic --no-input

    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Run Migrations and Staticfiles'

  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy Docker Image'
    inputs:
      azureSubscription: 'SP.DMAPPS-DEV'
      appType: webAppContainer
      WebAppName: 'dmapps-dev-docker'
      DockerNamespace: dmappsdevacr.azurecr.io
      DockerRepository: dmapps_img
      DockerImageTag: latest
      StartupCommand: init.sh
      AppSettings: >-
        -WEBSITES_PORT 8000
        -AAD_APP_ID "7c0933f3-9e00-4070-bcd8-bb48a4bec0f1"
        -AAD_APP_SECRET $(AAD_APP_SECRET)
        -AAD_AUTHORITY "https://login.microsoftonline.com/1594fdae-a1d9-4405-915d-011467234338"
        -AAD_AUTHORIZE_ENDPOINT "/oauth2/v2.0/authorize"
        -AAD_REDIRECT "https://dmapps-dev.azurewebsites.net/accounts/callback"
        -AAD_SCOPES  "openid user.read"
        -AAD_TOKEN_ENDPOINT "/oauth2/v2.0/token"
        -AZURE_STORAGE_ACCOUNT_NAME dmappsdev
        -DB_HOST "dmapps-dev-mysql.mysql.database.azure.com"
        -DB_MODE DEV
        -DB_NAME dmapps_dev
        -DB_PASSWORD $(DB_PASSWORD_DEV_TEST)
        -DB_PORT 3306
        -DB_USER "dmapps_user@dmapps-dev-mysql"
        -DEBUG True
        -DEPLOYMENT_STAGE DEV
        -SENDGRID_API_KEY $(SENDGRID_API_KEY)
        -SITE_FULL_URL "https://dmapps-dev.azurewebsites.net"
        -ALLOWED_HOST_TO_ADD "dmapps-dev-docker.azurewebsites.net"
        -SITE_FROM_EMAIL "DoNotReply.DMApps@Azure.Cloud.dfo-mpo.gc.ca"
        -SHOW_TICKETING_APP True
        -GEODJANGO False
        -SECRET_KEY $(SECRET_KEY)
        -GITHUB_API_KEY $(GITHUB_API_KEY)