pool: dmapps

trigger:
  - none

steps:
  - script: |
      # log into acr using msi
      az login --identity -u b9b8533b-430c-4b7a-95b7-0c8d43179f68
      az account set --subscription="IMTS DEV/TEST"
      az acr login --name dmappsdevtestacr
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Login to ACR using AZ CLI'

  - script: |
      # start a new .env file containing the docker build number
      echo "DOCKER_BUILD_NUMBER=$(Build.BuildNumber)" > .env

      # build the new docker image for the "latest" and the build number
      docker build \
        -t dmappsdevtestacr.azurecr.io/dmapps_img:latest \
        -t dmappsdevtestacr.azurecr.io/dmapps_img:$(Build.BuildNumber) .

      # push those images to ACR
      docker push dmappsdevtestacr.azurecr.io/dmapps_img:latest
      docker push dmappsdevtestacr.azurecr.io/dmapps_img:$(Build.BuildNumber)

      # if production tag is provided, do another build + push for the production tag
      if [ -n "$(productionTag)" ]
        then
        docker build -t dmappsdevtestacr.azurecr.io/dmapps_img:$(productionTag) .
        docker push dmappsdevtestacr.azurecr.io/dmapps_img:$(productionTag)
      else
        echo "No production tag provided."
      fi

    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Build Docker Images and Push to ACR'
