pool: dmapps

trigger:
  - master

steps:
  - script: |
      # install pre-requisites
      whoami
      python -V
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install -r requirements.txt
      python -m pip uninstall django-easy-pdf
      python -m pip install git+https://github.com/pawanvirsingh/django-easy-pdf.git#egg=django-easy-pdf
      mkdir media
      mkdir media/travel
      mkdir media/travel/temp
      mkdir media/projects
      mkdir media/projects/temp
      mkdir media/inventory
      mkdir media/inventory/temp
      mkdir media/ihub
      mkdir media/ihub/temp
      python manage.py collectstatic --no-input
      python manage.py migrate
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Install Prerequisites and Run Local Migrations '

  - script: |
      ./run_tests.sh
    condition: succeededOrFailed()
    displayName: 'Run tests'
